#include <cmsis.h>
#include "port_drv.h"
#include "clock.h"
#include "PinNames.h"

#include <stdio.h>
#include "raw_serial.h"

#if defined(RAW_SERIAL_ENABLE)
void raw_serial_init(void)
{
	MCLK_REGS->MCLK_AHBMASK |= MCLK_AHBMASK_HPB3(1);
	MCLK_REGS->MCLK_APBDMASK |= MCLK_APBDMASK_SERCOM4(1);
	
#if 0
	__disable_irq();
	CMCC_REGS->CMCC_CTRL = 1;
	__enable_irq();
#endif

	//PB08 = 40
	PORT_REGS->GROUP[1].PORT_PMUX[8 >> 1] = PORT_PMUX_PMUXE(3);
	PORT_REGS->GROUP[1].PORT_PINCFG[8] =
			PORT_PINCFG_PMUXEN(1) |
			PORT_PINCFG_DRVSTR(1);
	//PB09 = 41
	PORT_REGS->GROUP[1].PORT_PMUX[9 >> 1] |= PORT_PMUX_PMUXO(3);
	PORT_REGS->GROUP[1].PORT_PINCFG[9] =
			PORT_PINCFG_PMUXEN(1) |
			PORT_PINCFG_DRVSTR(1);

	//SERCOM4 / USART INT
	GCLK_REGS->GCLK_PCHCTRL[34] = GCLK_PCHCTRL_GEN_GCLK1 | GCLK_PCHCTRL_CHEN(1);
	GCLK_REGS->GCLK_PCHCTRL[3] = GCLK_PCHCTRL_GEN_GCLK1 | GCLK_PCHCTRL_CHEN(1);

	SERCOM4_REGS->USART_INT.SERCOM_CTRLA = SERCOM_USART_INT_CTRLA_SWRST(1);
	while (SERCOM4_REGS->USART_INT.SERCOM_CTRLA & SERCOM_USART_INT_CTRLA_SWRST(1));

	SERCOM4_REGS->USART_INT.SERCOM_CTRLA =
        SERCOM_USART_INT_CTRLA_MODE_USART_INT_CLK |
		SERCOM_USART_INT_CTRLA_SAMPR_16X_FRACTIONAL;

	uint32_t baud8 = (48000000 * 8) / (16 * 115200);
	SERCOM4_REGS->USART_INT.SERCOM_BAUD =
			SERCOM_USART_INT_BAUD_FRAC_FP(baud8 % 8) |
			SERCOM_USART_INT_BAUD_FRAC_BAUD(baud8 / 8);

    SERCOM4_REGS->USART_INT.SERCOM_CTRLA |=
		SERCOM_USART_INT_CTRLA_FORM_USART_FRAME_NO_PARITY |
		SERCOM_USART_INT_CTRLA_DORD_LSB;
	SERCOM4_REGS->USART_INT.SERCOM_CTRLB =
		SERCOM_USART_INT_CTRLB_CHSIZE_8_BIT |
		SERCOM_USART_INT_CTRLB_SBMODE_1_BIT;

	SERCOM4_REGS->USART_INT.SERCOM_CTRLA |=
        SERCOM_USART_INT_CTRLA_TXPO_PAD0 |
        SERCOM_USART_INT_CTRLA_RXPO_PAD1;

	SERCOM4_REGS->USART_INT.SERCOM_CTRLB |=
        SERCOM_USART_INT_CTRLB_TXEN(1) |
	    SERCOM_USART_INT_CTRLB_RXEN(1);

    SERCOM4_REGS->USART_INT.SERCOM_CTRLA |=
		SERCOM_USART_INT_CTRLA_ENABLE(1);
	while (SERCOM4_REGS->USART_INT.SERCOM_SYNCBUSY & SERCOM_USART_INT_SYNCBUSY_ENABLE(1));
}

void raw_serial_wait_for_empty(void)
{
	while (!(SERCOM4_REGS->USART_INT.SERCOM_INTFLAG & SERCOM_USART_INT_INTFLAG_DRE(1)));
}

void raw_serial_write(const char *str)
{
    for (int i=0; str[i]; i++) {
    	SERCOM4_REGS->USART_INT.SERCOM_DATA = SERCOM_USART_INT_DATA_DATA(str[i]);
		raw_serial_wait_for_empty();
    }

}

void raw_serial_printf(const char *fmt, ...)
{
	char buf[256];
	__builtin_va_list args;
	__builtin_va_start(args, fmt);
	vsnprintf(buf, 1024, fmt, args);
	__builtin_va_end(args);
	raw_serial_write(buf);
}
#endif
